name: Deploy to cPanel via Git
# Create deployment branch with built files for cPanel Git deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: "https://yacaebicwatkntvvobsn.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY2FlYmljd2F0a250dnZvYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2NjMsImV4cCI6MjA2OTI4ODY2M30.opm419ZQV_6BlJA-ArexehJM-n-Rhkpbjk-z6KIcDO8"
        
    - name: Prepare deployment files
      run: |
        # Verify build completed successfully
        if [ ! -d "dist" ]; then
          echo "Build failed - dist directory not found"
          exit 1
        fi
        
        # Configure git
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Create deployment branch from current state
        git checkout -b deployment
        
        # Clear everything except .git and dist
        find . -maxdepth 1 ! -name '.git' ! -name 'dist' ! -name '.' ! -name '..' -exec rm -rf {} +
        
        # Move dist contents to root
        mv dist/* .
        rmdir dist
        
        # Add .htaccess for subdirectory routing
        cat > .htaccess << 'EOL'
        DirectoryIndex index.html
        Options -Indexes
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /my-buom-app/index.html [L]
        EOL
        
        # Commit deployment files
        git add .
        git commit -m "Deploy: $(date '+%Y-%m-%d %H:%M:%S')"
        
    - name: Push to deployment branch
      run: |
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git deployment --force
