name: Deploy to cPanel
# Fixed dependency issue - removed invalid @radix-ui/react-sheet package
# Using lftp with SSL certificate verification disabled (Copilot suggestion)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: https://yacaebicwatkntvvobsn.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY2FlYmljd2F0a250dnZvYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2NjMsImV4cCI6MjA2OTI4ODY2M30.opm419ZQV_6BlJA-ArexehJM-n-Rhkpbjk-z6KIcDO8
        
    - name: List build files
      run: ls -la dist/
      
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
      
    - name: Deploy via FTP
      run: |
        lftp -c "
        set ssl:verify-certificate no
        open ftp://ftp.buom.app
        user my-buom-app@sids.buom.app ${{ secrets.FTP_PASSWORD }}
        lcd dist
        cd public_html
        mirror --reverse --delete --verbose --exclude-glob .git*
        bye
        "
