name: Deploy to cPanel via Git
# Create deployment branch with built files for cPanel Git deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: "https://yacaebicwatkntvvobsn.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY2FlYmljd2F0a250dnZvYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2NjMsImV4cCI6MjA2OTI4ODY2M30.opm419ZQV_6BlJA-ArexehJM-n-Rhkpbjk-z6KIcDO8"
        
    - name: Prepare deployment files
      run: |
        # Create deployment branch with built files
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Create a new branch for deployment
        git checkout -b deployment
        
        # Copy built files to root (cPanel will serve from repository root)
        cp -r dist/* .
        
        # Create .htaccess for subdirectory deployment
        echo "DirectoryIndex index.html" > .htaccess
        echo "Options -Indexes" >> .htaccess
        
        # Add built files to git
        git add -A
        git commit -m "Deploy built files" || echo "No changes to commit"
        
    - name: Push to deployment branch
      run: |
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git deployment --force
