name: Simple Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install and Build
      run: |
        npm install --legacy-peer-deps
        npm run build
      env:
        VITE_SUPABASE_URL: "https://yacaebicwatkntvvobsn.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY2FlYmljd2F0a250dnZvYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2NjMsImV4cCI6MjA2OTI4ODY2M30.opm419ZQV_6BlJA-ArexehJM-n-Rhkpbjk-z6KIcDO8"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
